"""
    AYLIEN News API

    The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client.   # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: support@aylien.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aylien_news_api
from aylien_news_api.model.deprecated_related_stories import DeprecatedRelatedStories
from aylien_news_api.model.deprecated_story import DeprecatedStory
from aylien_news_api.model.related_stories import RelatedStories
globals()['DeprecatedRelatedStories'] = DeprecatedRelatedStories
globals()['DeprecatedStory'] = DeprecatedStory
globals()['RelatedStories'] = RelatedStories
from aylien_news_api.model.one_of_related_stories_deprecated_related_stories import OneOfRelatedStoriesDeprecatedRelatedStories


class TestOneOfRelatedStoriesDeprecatedRelatedStories(unittest.TestCase):
    """OneOfRelatedStoriesDeprecatedRelatedStories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfRelatedStoriesDeprecatedRelatedStories(self):
        """Test OneOfRelatedStoriesDeprecatedRelatedStories"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OneOfRelatedStoriesDeprecatedRelatedStories()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
