# flake8: noqa

"""
    AYLIEN News API

    The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client.   # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: support@aylien.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "5.0.0"

# import ApiClient
from aylien_news_api.api_client import ApiClient

# import Configuration
from aylien_news_api.configuration import Configuration

# import exceptions
from aylien_news_api.exceptions import OpenApiException
from aylien_news_api.exceptions import ApiAttributeError
from aylien_news_api.exceptions import ApiTypeError
from aylien_news_api.exceptions import ApiValueError
from aylien_news_api.exceptions import ApiKeyError
from aylien_news_api.exceptions import ApiException
