# coding: utf-8

# flake8: noqa

"""
    AYLIEN News API

    The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client.   # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: support@aylien.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "3.0.0"

# import apis into sdk package
from aylien_news_api.api.default_api import DefaultApi

# import ApiClient
from aylien_news_api.api_client import ApiClient
from aylien_news_api.configuration import Configuration
from aylien_news_api.exceptions import OpenApiException
from aylien_news_api.exceptions import ApiTypeError
from aylien_news_api.exceptions import ApiValueError
from aylien_news_api.exceptions import ApiKeyError
from aylien_news_api.exceptions import ApiException
# import models into sdk package
from aylien_news_api.models.author import Author
from aylien_news_api.models.autocomplete import Autocomplete
from aylien_news_api.models.autocompletes import Autocompletes
from aylien_news_api.models.category import Category
from aylien_news_api.models.category_links import CategoryLinks
from aylien_news_api.models.cluster import Cluster
from aylien_news_api.models.clusters import Clusters
from aylien_news_api.models.coverages import Coverages
from aylien_news_api.models.entities import Entities
from aylien_news_api.models.entity import Entity
from aylien_news_api.models.entity_links import EntityLinks
from aylien_news_api.models.error import Error
from aylien_news_api.models.error_links import ErrorLinks
from aylien_news_api.models.errors import Errors
from aylien_news_api.models.histogram_interval import HistogramInterval
from aylien_news_api.models.histograms import Histograms
from aylien_news_api.models.location import Location
from aylien_news_api.models.media import Media
from aylien_news_api.models.rank import Rank
from aylien_news_api.models.rankings import Rankings
from aylien_news_api.models.related_stories import RelatedStories
from aylien_news_api.models.representative_story import RepresentativeStory
from aylien_news_api.models.scope import Scope
from aylien_news_api.models.sentiment import Sentiment
from aylien_news_api.models.sentiments import Sentiments
from aylien_news_api.models.share_count import ShareCount
from aylien_news_api.models.share_counts import ShareCounts
from aylien_news_api.models.source import Source
from aylien_news_api.models.stories import Stories
from aylien_news_api.models.story import Story
from aylien_news_api.models.story_cluster import StoryCluster
from aylien_news_api.models.story_links import StoryLinks
from aylien_news_api.models.story_translations import StoryTranslations
from aylien_news_api.models.story_translations_en import StoryTranslationsEn
from aylien_news_api.models.summary import Summary
from aylien_news_api.models.time_series import TimeSeries
from aylien_news_api.models.time_series_list import TimeSeriesList
from aylien_news_api.models.trend import Trend
from aylien_news_api.models.trends import Trends

